---
title: "Data_Cleaning"
author: "Caleb Neale"
date: "3/23/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing Data
```{r}
fac_names = read.csv("fac_names_depts.csv")
salaries = read.csv("2020_cav_daily_data.csv")
```

# Applying gender funciton to fac_names
Documentation and methodology found here, see page 3-4:
https://cran.r-project.org/web/packages/gender/gender.pdf
```{r}
library(gender)
library(tidyr)
library(dplyr)
library(tidyverse)

# separate first names
fac_names$full_name %>% strsplit(" ") -> fac_names$names
fac_names$num_names = fac_names$names %>% sapply(length)
fac_names$first_name = fac_names$names %>% sapply("[", 1)

for (i in 1:nrow(fac_names)){
  fac_names$last_name[i] <- fac_names$names[i][[1]][fac_names$num_names[i]]
}


# assume oldest professor is 75, youngest is 35

fac_names$first_name %>% gender(years=c(1946, 1986)) %>% select("name", "gender") -> name_guesses

# merge gender data back into fac_names
fac_names %>% left_join(name_guesses, by=c("first_name" = "name")) -> fac_names_gender

# remove duplicates generated by merge
fac_names_gender %>% distinct() -> fac_names_gender

# check counts
fac_names_gender %>% count(gender)

# save as csv
fac_names_gender %>% write.csv("fac_names_gender.csv")

```

# Applying gender funtion to salaries data
```{r}

# assume oldest professor is 75, youngest is 35

salaries$First.Name %>% gender(years=c(1946, 1986)) %>% select("name", "gender") -> name_guesses_salaries

# merge gender data back into salaries
salaries %>% left_join(name_guesses_salaries, by=c("First.Name" = "name")) -> salaries_gender

# remove duplicates generated by merge
salaries_gender %>% distinct() -> salaries_gender

# check counts
salaries_gender %>% count(gender)

# save as csv
salaries_gender %>% write.csv("fac_names_gender.csv")

```
# Join data, filter NAs and clean titles 
```{r}
joined = left_join(fac_names_gender, salaries, by = c("first_name" = "First.Name", "last_name" = "Last.Name"))


filtered = filter(joined, !is.na(Base.Pay))
filtered %>% select(c('first_name', "last_name", "title", "school", "department", "gender", "Base.Pay")) -> filtered


filtered$cleanedTitle <- str_match(filtered$title, "(Assistant Professor)|(Associate Professor)|(^Professor)|(Lecturer)|(Senior Lecturer)|(Instructor)")

filtered %>% select(-title) -> filtered

write.csv(filtered, "clean_combined_data.csv")


```


